spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ec-201904b
    username: postgres
    password: postgres
  jmx:
    default-domain: ec-201904b
  mail:
    host: smtp.gmail.com
    port: 587
    username: xxxxxxxxbk
    password: xxxxxxxxbk
    properties:
      mail.smtp:
        auth: true
        starttls.enable: true
server:
  servlet:
    context-path: /ec-201904b