spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/student
    username: postgres
    password: postgres
#  jmx:
#    default-domain: ec-201904b
#server:
#  servlet:
#    context-path: /ec-201904b
  
